## ZVV Transit Notebook

The point of this notebook is to come up with a structured file, which includes the necessary stations and lines needed for the Mister X ZÃ¼rich application.

In [1]:
# Imports
import pandas as pd
import numpy as np

At first we want to specify, which lines we want to look and and get their corresponding route ids and their type of transportation.

In [2]:
routes = pd.read_csv(r'routes.txt')
routes = routes[["route_id", "route_short_name"]]
line_labels = np.array(["2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "31", "32", "33"])
routes = routes[routes.route_short_name.isin(line_labels)]

tram_routes = routes[routes.route_id.str.startswith("1-")].assign(route_type="tram")
bus_routes = routes[routes.route_id.str.startswith("2-")].assign(route_type="bus")

routes = pd.concat([tram_routes, bus_routes], sort=False)
routes

        route_id route_short_name route_type
6   1-10-P-j21-1               10       tram
9   1-11-P-j21-1               11       tram
10  1-12-P-j21-1               12       tram
11  1-13-P-j21-1               13       tram
12  1-14-P-j21-1               14       tram
13  1-15-P-j21-1               15       tram
17   1-2-P-j21-1                2       tram
18   1-3-P-j21-1                3       tram
20   1-4-P-j21-1                4       tram
23   1-5-P-j21-1                5       tram
24   1-6-P-j21-1                6       tram
25   1-7-P-j21-1                7       tram
26   1-8-P-j21-1                8       tram
27   1-9-P-j21-1                9       tram
42  2-31-P-j21-1               31        bus
43  2-32-P-j21-1               32        bus
49  2-33-P-j21-1               33        bus

In [3]:
trips = pd.read_csv(r'trips.txt')
trips = trips[["route_id","trip_id"]]
trips = trips[trips.route_id.isin(routes.route_id)]
trips
trips_by_route_id = trips.groupby(["route_id"])["trip_id"].apply(list).reset_index(name='trip_ids')
trips_by_route_id

        route_id                                           trip_ids
0   1-10-P-j21-1  [10.T3.1-10-P-j21-1.2.R, 100.T0.1-10-P-j21-1.4...
1   1-11-P-j21-1  [100.T0.1-11-P-j21-1.13.R, 1004.T0.1-11-P-j21-...
2   1-12-P-j21-1  [1.T2.1-12-P-j21-1.1.R, 10.T2.1-12-P-j21-1.1.R...
3   1-13-P-j21-1  [1.T2.1-13-P-j21-1.2.R, 1.T3.1-13-P-j21-1.2.R,...
4   1-14-P-j21-1  [10.T2.1-14-P-j21-1.4.R, 10.T3.1-14-P-j21-1.2....
5   1-15-P-j21-1  [1.T2.1-15-P-j21-1.5.R, 1.T3.1-15-P-j21-1.5.R,...
6    1-2-P-j21-1  [1.T2.1-2-P-j21-1.1.R, 10.T2.1-2-P-j21-1.4.R, ...
7    1-3-P-j21-1  [1.T2.1-3-P-j21-1.7.R, 10.T2.1-3-P-j21-1.8.R, ...
8    1-4-P-j21-1  [1.T2.1-4-P-j21-1.5.R, 1.T3.1-4-P-j21-1.5.R, 1...
9    1-5-P-j21-1  [1.T3.1-5-P-j21-1.1.R, 10.T2.1-5-P-j21-1.2.R, ...
10   1-6-P-j21-1  [10.T2.1-6-P-j21-1.37.R, 100.T2.1-6-P-j21-1.39...
11   1-7-P-j21-1  [1.T2.1-7-P-j21-1.6.R, 1.T3.1-7-P-j21-1.6.R, 1...
12   1-8-P-j21-1  [1004.T0.1-8-P-j21-1.6.R, 1006.T0.1-8-P-j21-1....
13   1-9-P-j21-1  [10.T2.1-9-P-j21-1.14.R, 10.T3.1-9-P-j21-1.14....
14  2-31-P-j21-1  [1.T2.2-31-P-j21-1.1.R, 1.T3.2-31-P-j21-1.1.R,...
15  2-32-P-j21-1  [1.T2.2-32-P-j21-1.1.R, 1.T3.2-32-P-j21-1.1.R,...
16  2-33-P-j21-1  [1.T2.2-33-P-j21-1.1.R, 1.T3.2-33-P-j21-1.1.R,...

In [4]:
stop_times = pd.read_csv(r'stop_times.txt')
stop_times = stop_times[["trip_id","stop_id","stop_sequence"]]
stop_times = stop_times[stop_times.trip_id.isin(trips.trip_id)]
stop_times

                        trip_id              stop_id  stop_sequence
0         2.T2.1-9-P-j21-1.14.R   gen:23026:1643:1:1              1
1         2.T2.1-9-P-j21-1.14.R   gen:23026:2666:1:1              2
2         2.T2.1-9-P-j21-1.14.R   gen:23026:2814:1:1              3
3         2.T2.1-9-P-j21-1.14.R   gen:23026:2326:1:1              4
4         2.T2.1-9-P-j21-1.14.R   gen:23026:2294:1:1              5
...                         ...                  ...            ...
513757  497.T0.2-33-P-j21-1.8.H   gen:23026:1252:1:1              3
513758  497.T0.2-33-P-j21-1.8.H  gen:23026:2147:1:10              4
513759  497.T0.2-33-P-j21-1.8.H  gen:23026:3155:1:10              5
513760  497.T0.2-33-P-j21-1.8.H  gen:23026:1320:1:10              6
513761  497.T0.2-33-P-j21-1.8.H  gen:23026:2680:2:10              7

[505583 rows x 3 columns]

In [5]:
ordered_stops_by_trip_id = stop_times.groupby(["trip_id"])["stop_id"].apply(list).reset_index(name='ordered_stop_ids')
ordered_stops_by_trip_id

,trip_id,ordered_stop_ids
0,1.T2.1-12-P-j21-1.1.R,"[gen:23026:2575:1:1, gen:23026:3785:3:1, gen:2..."
1,1.T2.1-13-P-j21-1.2.R,"[gen:23026:2950:1:0, gen:23026:586:1:1, gen:23..."
2,1.T2.1-15-P-j21-1.5.R,"[gen:23026:3039:1:1, gen:23026:440:1:3, gen:23..."
3,1.T2.1-2-P-j21-1.1.R,"[gen:23026:1357:1:1, gen:23026:1579:1:1, gen:2..."
4,1.T2.1-3-P-j21-1.7.R,"[gen:23026:1357:1:1, gen:23026:1579:1:1, gen:2..."
...,...,...
20391,999.T0.1-4-P-j21-1.27.H,"[gen:23026:5001:2:0, gen:23026:6648:1:0, gen:2..."
20392,999.T0.1-6-P-j21-1.27.H,"[gen:23026:3005:1:0, gen:23026:2618:1:0, gen:2..."
20393,999.T0.1-8-P-j21-1.22.R,"[gen:23026:1430:1:1, gen:23026:1278:1:1, gen:2..."
20394,999.T2.1-13-P-j21-1.37.H,"[gen:23026:872:1:0, gen:23026:2935:1:0, gen:23..."
20395,999.T2.1-6-P-j21-1.27.H,"[gen:23026:3005:1:0, gen:23026:2618:1:0, gen:2..."

In [6]:
ordered_stops_by_trip_id['length'] = ordered_stops_by_trip_id["ordered_stop_ids"].apply(len)
ordered_stops_by_trip_id

,trip_id,ordered_stop_ids,length
0,1.T2.1-12-P-j21-1.1.R,"[gen:23026:2575:1:1, gen:23026:3785:3:1, gen:2...",18
1,1.T2.1-13-P-j21-1.2.R,"[gen:23026:2950:1:0, gen:23026:586:1:1, gen:23...",31
2,1.T2.1-15-P-j21-1.5.R,"[gen:23026:3039:1:1, gen:23026:440:1:3, gen:23...",13
3,1.T2.1-2-P-j21-1.1.R,"[gen:23026:1357:1:1, gen:23026:1579:1:1, gen:2...",17
4,1.T2.1-3-P-j21-1.7.R,"[gen:23026:1357:1:1, gen:23026:1579:1:1, gen:2...",9
...,...,...,...
20391,999.T0.1-4-P-j21-1.27.H,"[gen:23026:5001:2:0, gen:23026:6648:1:0, gen:2...",26
20392,999.T0.1-6-P-j21-1.27.H,"[gen:23026:3005:1:0, gen:23026:2618:1:0, gen:2...",26
20393,999.T0.1-8-P-j21-1.22.R,"[gen:23026:1430:1:1, gen:23026:1278:1:1, gen:2...",20
20394,999.T2.1-13-P-j21-1.37.H,"[gen:23026:872:1:0, gen:23026:2935:1:0, gen:23...",31
20395,999.T2.1-6-P-j21-1.27.H,"[gen:23026:3005:1:0, gen:23026:2618:1:0, gen:2...",26

In [7]:
def get_trip_length(x):
    return ordered_stops_by_trip_id.loc[ordered_stops_by_trip_id["trip_id"] == x]["length"].to_numpy()[0]

def choose_element_with_max_length_list(x):
    max_trip = x[0]
    for trip in x:
        if get_trip_length(trip) > get_trip_length(max_trip):
            max_trip = trip
    return max_trip

In [8]:
trips_by_route_id["max_trip_id"] = trips_by_route_id["trip_ids"].apply(choose_element_with_max_length_list)

In [9]:
trips_by_route_id

,route_id,trip_ids,max_trip_id
0,1-10-P-j21-1,"[10.T3.1-10-P-j21-1.2.R, 100.T0.1-10-P-j21-1.4...",1010.T0.1-10-P-j21-1.24.H
1,1-11-P-j21-1,"[100.T0.1-11-P-j21-1.13.R, 1004.T0.1-11-P-j21-...",100.T0.1-11-P-j21-1.13.R
2,1-12-P-j21-1,"[1.T2.1-12-P-j21-1.1.R, 10.T2.1-12-P-j21-1.1.R...",1.T2.1-12-P-j21-1.1.R
3,1-13-P-j21-1,"[1.T2.1-13-P-j21-1.2.R, 1.T3.1-13-P-j21-1.2.R,...",1.T2.1-13-P-j21-1.2.R
4,1-14-P-j21-1,"[10.T2.1-14-P-j21-1.4.R, 10.T3.1-14-P-j21-1.2....",10.T2.1-14-P-j21-1.4.R
5,1-15-P-j21-1,"[1.T2.1-15-P-j21-1.5.R, 1.T3.1-15-P-j21-1.5.R,...",117.T2.1-15-P-j21-1.6.R
6,1-2-P-j21-1,"[1.T2.1-2-P-j21-1.1.R, 10.T2.1-2-P-j21-1.4.R, ...",10.T2.1-2-P-j21-1.4.R
7,1-3-P-j21-1,"[1.T2.1-3-P-j21-1.7.R, 10.T2.1-3-P-j21-1.8.R, ...",10.T2.1-3-P-j21-1.8.R
8,1-4-P-j21-1,"[1.T2.1-4-P-j21-1.5.R, 1.T3.1-4-P-j21-1.5.R, 1...",10.T2.1-4-P-j21-1.16.R
9,1-5-P-j21-1,"[1.T3.1-5-P-j21-1.1.R, 10.T2.1-5-P-j21-1.2.R, ...",313.T2.1-5-P-j21-1.22.H
10,1-6-P-j21-1,"[10.T2.1-6-P-j21-1.37.R, 100.T2.1-6-P-j21-1.39...",100.T2.1-6-P-j21-1.39.R
11,1-7-P-j21-1,"[1.T2.1-7-P-j21-1.6.R, 1.T3.1-7-P-j21-1.6.R, 1...",10.T2.1-7-P-j21-1.7.R
12,1-8-P-j21-1,"[1004.T0.1-8-P-j21-1.6.R, 1006.T0.1-8-P-j21-1....",2070.T0.1-8-P-j21-1.45.H
13,1-9-P-j21-1,"[10.T2.1-9-P-j21-1.14.R, 10.T3.1-9-P-j21-1.14....",1004.T0.1-9-P-j21-1.24.H
14,2-31-P-j21-1,"[1.T2.2-31-P-j21-1.1.R, 1.T3.2-31-P-j21-1.1.R,...",1000.T0.2-31-P-j21-1.11.H
15,2-32-P-j21-1,"[1.T2.2-32-P-j21-1.1.R, 1.T3.2-32-P-j21-1.1.R,...",10.T2.2-32-P-j21-1.4.R
16,2-33-P-j21-1,"[1.T2.2-33-P-j21-1.1.R, 1.T3.2-33-P-j21-1.1.R,...",10.T2.2-33-P-j21-1.3.R

In [10]:
def get_stops(route_id):
    max_trip_id = trips_by_route_id.loc[trips_by_route_id["route_id"] == route_id]["max_trip_id"].to_numpy()[0]
    ordered_stops = ordered_stops_by_trip_id.loc[ordered_stops_by_trip_id["trip_id"] == max_trip_id]["ordered_stop_ids"].to_numpy()[0]
    return ordered_stops
    
lines_tram_bus = routes
lines_tram_bus["ordered_stops"] = routes["route_id"].apply(get_stops)
lines_tram_bus = lines_tram_bus.reset_index(drop=True)
lines_tram_bus

,route_id,route_short_name,route_type,ordered_stops
0,1-10-P-j21-1,10,tram,"[gen:23026:6232:2:0, gen:23026:3027:3:0, gen:2..."
1,1-11-P-j21-1,11,tram,"[gen:23026:2549:1:0, gen:23026:894:1:1, gen:23..."
2,1-12-P-j21-1,12,tram,"[gen:23026:2575:1:1, gen:23026:3785:3:1, gen:2..."
3,1-13-P-j21-1,13,tram,"[gen:23026:2950:1:0, gen:23026:586:1:1, gen:23..."
4,1-14-P-j21-1,14,tram,"[gen:23026:2680:1:1, gen:23026:2160:1:1, gen:2..."
5,1-15-P-j21-1,15,tram,"[gen:23026:3039:1:1, gen:23026:440:1:3, gen:23..."
6,1-2-P-j21-1,2,tram,"[gen:23026:3041:1:0, gen:23026:2907:1:1, gen:2..."
7,1-3-P-j21-1,3,tram,"[gen:23026:1430:1:0, gen:23026:1278:1:1, gen:2..."
8,1-4-P-j21-1,4,tram,"[gen:23026:3041:1:1, gen:23026:2907:1:1, gen:2..."
9,1-5-P-j21-1,5,tram,"[gen:23026:1334:1:0, gen:23026:1507:1:0, gen:2..."
10,1-6-P-j21-1,6,tram,"[gen:23026:2872:1:0, gen:23026:592:1:0, gen:23..."
11,1-7-P-j21-1,7,tram,"[gen:23026:2950:1:0, gen:23026:586:1:1, gen:23..."
12,1-8-P-j21-1,8,tram,"[gen:23026:2447:1:0, gen:23026:467:1:0, gen:23..."
13,1-9-P-j21-1,9,tram,"[gen:23026:1220:1:0, gen:23026:88:1:0, gen:230..."
14,2-31-P-j21-1,31,bus,"[gen:23026:6998:1:10, gen:23026:1640:1:0, gen:..."
15,2-32-P-j21-1,32,bus,"[gen:23026:2596:1:10, gen:23026:1143:1:11, gen..."
16,2-33-P-j21-1,33,bus,"[gen:23026:2680:2:10, gen:23026:1320:1:11, gen..."

In [11]:
stops = pd.read_csv(r'stops.txt')
stops = stops[["stop_id","stop_name","stop_lat","stop_lon"]]
stops

                 stop_id                   stop_name   stop_lat  stop_lon
0     ch:23026:1198:1:52    Wiesendangen, Hinterdorf  47.522019  8.794354
1     ch:23026:1902:1:80             Benken ZH, Dorf  47.652405  8.655322
2     ch:23026:1902:1:81             Benken ZH, Dorf  47.652423  8.655474
3     ch:23026:2095:1:52      DÃ¼bendorf, Ringstrasse  47.400040  8.607379
4     ch:23026:2283:2:12  Winterthur, Schulhaus Seen  47.483295  8.761592
...                  ...                         ...        ...       ...
5631           Parent971             Germaniastrasse  47.387130  8.552222
5632           Parent974               Gewerbeschule  47.498039  8.732568
5633           Parent983               Industriepark  47.501371  8.761826
5634           Parent994                     Bahnhof  47.430567  8.559355
5635           Parent998                 Glattwiesen  47.401603  8.581759

[5636 rows x 4 columns]

In [12]:
def get_station_names(ordered_stops):
    ordered_stop_names = []
    for stop_id in ordered_stops:
        stop_name = stops.loc[stops["stop_id"] == stop_id]["stop_name"].to_numpy()[0]
        ordered_stop_names.append(stop_name)
    return ordered_stop_names

lines_tram_bus["ordered_stop_names"] = lines_tram_bus["ordered_stops"].apply(get_station_names)
lines_tram_bus

,route_id,route_short_name,route_type,ordered_stops,ordered_stop_names
0,1-10-P-j21-1,10,tram,"[gen:23026:6232:2:0, gen:23026:3027:3:0, gen:2...","[ZÃ¼rich Flughafen, Fracht, ZÃ¼rich Flughafen, B..."
1,1-11-P-j21-1,11,tram,"[gen:23026:2549:1:0, gen:23026:894:1:1, gen:23...","[ZÃ¼rich, Rehalp, ZÃ¼rich, Friedhof EnzenbÃ¼hl, Z..."
2,1-12-P-j21-1,12,tram,"[gen:23026:2575:1:1, gen:23026:3785:3:1, gen:2...","[ZÃ¼rich, Bahnhof Stettbach, DÃ¼bendorf, Ringwie..."
3,1-13-P-j21-1,13,tram,"[gen:23026:2950:1:0, gen:23026:586:1:1, gen:23...","[ZÃ¼rich, Wollishoferplatz, ZÃ¼rich, Butzenstras..."
4,1-14-P-j21-1,14,tram,"[gen:23026:2680:1:1, gen:23026:2160:1:1, gen:2...","[ZÃ¼rich, Triemli, ZÃ¼rich, Schaufelbergerstrass..."
5,1-15-P-j21-1,15,tram,"[gen:23026:3039:1:1, gen:23026:440:1:3, gen:23...","[ZÃ¼rich, Bahnhof Stadelhofen, ZÃ¼rich, Bellevue..."
6,1-2-P-j21-1,2,tram,"[gen:23026:3041:1:0, gen:23026:2907:1:1, gen:2...","[ZÃ¼rich, Bahnhof Tiefenbrunnen, ZÃ¼rich, Wildba..."
7,1-3-P-j21-1,3,tram,"[gen:23026:1430:1:0, gen:23026:1278:1:1, gen:2...","[ZÃ¼rich, Klusplatz, ZÃ¼rich, HÃ¶lderlinstrasse, ..."
8,1-4-P-j21-1,4,tram,"[gen:23026:3041:1:1, gen:23026:2907:1:1, gen:2...","[ZÃ¼rich, Bahnhof Tiefenbrunnen, ZÃ¼rich, Wildba..."
9,1-5-P-j21-1,5,tram,"[gen:23026:1334:1:0, gen:23026:1507:1:0, gen:2...","[ZÃ¼rich, UniversitÃ¤t Irchel, ZÃ¼rich, Langmauer..."
10,1-6-P-j21-1,6,tram,"[gen:23026:2872:1:0, gen:23026:592:1:0, gen:23...","[ZÃ¼rich, WerdhÃ¶lzli, ZÃ¼rich, BÃ¤ndliweg, ZÃ¼rich..."
11,1-7-P-j21-1,7,tram,"[gen:23026:2950:1:0, gen:23026:586:1:1, gen:23...","[ZÃ¼rich, Wollishoferplatz, ZÃ¼rich, Butzenstras..."
12,1-8-P-j21-1,8,tram,"[gen:23026:2447:1:0, gen:23026:467:1:0, gen:23...","[ZÃ¼rich, Hardturm, ZÃ¼rich, Bernoulli-HÃ¤user, Z..."
13,1-9-P-j21-1,9,tram,"[gen:23026:1220:1:0, gen:23026:88:1:0, gen:230...","[ZÃ¼rich, Hirzenbach, ZÃ¼rich, Altried, ZÃ¼rich, ..."
14,2-31-P-j21-1,31,bus,"[gen:23026:6998:1:10, gen:23026:1640:1:0, gen:...","[ZÃ¼rich, Hermetschloo, ZÃ¼rich, Micafil, ZÃ¼rich..."
15,2-32-P-j21-1,32,bus,"[gen:23026:2596:1:10, gen:23026:1143:1:11, gen...","[ZÃ¼rich, Strassenverkehrsamt, ZÃ¼rich, Hegianwa..."
16,2-33-P-j21-1,33,bus,"[gen:23026:2680:2:10, gen:23026:1320:1:11, gen...","[ZÃ¼rich, Triemli, ZÃ¼rich, In der Ey, ZÃ¼rich, S..."

In [13]:
lines_tram_bus_csv = lines_tram_bus.to_csv("lines_tram_bus", index=False)

In [14]:
list_of_stations = []
for station_list in lines_tram_bus["ordered_stop_names"]:
    list_of_stations += station_list
list_of_stations = list(set(list_of_stations))
list_of_stations
len(list_of_stations)

249

In [15]:
station_info = pd.DataFrame(columns = ["name", "stop_lat", "stop_lon", "reachable_by_tram", "reachable_by_bus"])
station_info["name"] = list_of_stations

def get_stop_lat(stop_name):
    return stops.loc[stops["stop_name"] == stop_name]["stop_lat"].to_numpy()[0]

def get_stop_lon(stop_name):
    return stops.loc[stops["stop_name"] == stop_name]["stop_lon"].to_numpy()[0]

station_info["stop_lat"] = station_info["name"].apply(get_stop_lat)
station_info["stop_lon"] = station_info["name"].apply(get_stop_lon)

station_info["reachable_by_tram"] = np.empty((len(station_info), 0)).tolist()
station_info["reachable_by_bus"] = np.empty((len(station_info), 0)).tolist()

station_info = station_info.set_index(["name"])

station_info

,stop_lat,stop_lon,reachable_by_tram,reachable_by_bus
name,,,,
"ZÃ¼rich, Laubegg",47.358786,8.517224,[],[]
"ZÃ¼rich, Zypressenstrasse",47.376662,8.513972,[],[]
"ZÃ¼rich, Lochergut",47.375366,8.517826,[],[]
"ZÃ¼rich, Sihlpost / HB",47.376339,8.534570,[],[]
"ZÃ¼rich, Seebach",47.421694,8.549958,[],[]
...,...,...,...,...
"ZÃ¼rich, Feldeggstrasse",47.360490,8.552042,[],[]
"ZÃ¼rich, FÃ¶rrlibuckstrasse",47.392220,8.517439,[],[]
"ZÃ¼rich, Uetlihof",47.356589,8.513819,[],[]
"ZÃ¼rich, Bahnhof Enge/Bederstr.",47.364536,8.530222,[],[]
"ZÃ¼rich, Wartau",47.402667,8.492098,[],[]

In [16]:
station_info["reachable_by_tram"] = np.empty((len(station_info), 0)).tolist()
station_info["reachable_by_bus"] = np.empty((len(station_info), 0)).tolist()

for i in range(lines_tram_bus.shape[0]):
    ordered_stop_names = lines_tram_bus.loc[i]["ordered_stop_names"]
    if lines_tram_bus.loc[i]["route_type"]=="tram":
        station_info.loc[ordered_stop_names[0],"reachable_by_tram"].extend([ordered_stop_names[1]])
        for j in range(1,len(lines_tram_bus.loc[i]["ordered_stop_names"])-1):
            station_info.loc[ordered_stop_names[j],"reachable_by_tram"].extend([ordered_stop_names[j-1],ordered_stop_names[j+1]])
        station_info.loc[ordered_stop_names[-1],"reachable_by_tram"].extend([ordered_stop_names[-2]])
    elif lines_tram_bus.loc[i]["route_type"]=="bus":
        station_info.loc[ordered_stop_names[0],"reachable_by_bus"].extend([ordered_stop_names[1]])
        for j in range(1,len(lines_tram_bus.loc[i]["ordered_stop_names"])-1):
            station_info.loc[ordered_stop_names[j],"reachable_by_bus"].extend([ordered_stop_names[j-1],ordered_stop_names[j+1]])
        station_info.loc[ordered_stop_names[-1],"reachable_by_bus"].extend([ordered_stop_names[-2]])
    else:
        print("ERROR")
 
station_info

,stop_lat,stop_lon,reachable_by_tram,reachable_by_bus
name,,,,
"ZÃ¼rich, Laubegg",47.358786,8.517224,"[ZÃ¼rich, Saalsporthalle, ZÃ¼rich, Uetlihof, ZÃ¼r...",[]
"ZÃ¼rich, Zypressenstrasse",47.376662,8.513972,"[ZÃ¼rich, Lochergut, ZÃ¼rich, Albisriederplatz, ...",[]
"ZÃ¼rich, Lochergut",47.375366,8.517826,"[ZÃ¼rich,Kalkbreite/Bhf.Wiedikon, ZÃ¼rich, Zypre...",[]
"ZÃ¼rich, Sihlpost / HB",47.376339,8.534570,"[ZÃ¼rich, Stauffacher, ZÃ¼rich, LÃ¶wenplatz, ZÃ¼ri...","[ZÃ¼rich, Kanonengasse, ZÃ¼rich, LÃ¶wenplatz]"
"ZÃ¼rich, Seebach",47.421694,8.549958,"[ZÃ¼rich, Seebacherplatz]",[]
...,...,...,...,...
"ZÃ¼rich, Feldeggstrasse",47.360490,8.552042,"[ZÃ¼rich, HÃ¶schgasse, ZÃ¼rich, Kreuzstrasse, ZÃ¼r...",[]
"ZÃ¼rich, FÃ¶rrlibuckstrasse",47.392220,8.517439,"[ZÃ¼rich, Fischerweg, ZÃ¼rich, Escher-Wyss-Platz...",[]
"ZÃ¼rich, Uetlihof",47.356589,8.513819,"[ZÃ¼rich, Laubegg, ZÃ¼rich, Strassenverkehrsamt]",[]
"ZÃ¼rich, Bahnhof Enge/Bederstr.",47.364536,8.530222,"[ZÃ¼rich, Tunnelstrasse, ZÃ¼rich, Waffenplatzstr...",[]
"ZÃ¼rich, Wartau",47.402667,8.492098,"[ZÃ¼rich, Zwielplatz, ZÃ¼rich, Winzerstrasse]",[]

In [17]:
def make_values_unique(l):
    return list(set(l))

    
station_info["reachable_by_tram"] = station_info["reachable_by_tram"].apply(make_values_unique)
station_info["reachable_by_bus"] = station_info["reachable_by_bus"].apply(make_values_unique)
station_info

,stop_lat,stop_lon,reachable_by_tram,reachable_by_bus
name,,,,
"ZÃ¼rich, Laubegg",47.358786,8.517224,"[ZÃ¼rich, Uetlihof, ZÃ¼rich, Saalsporthalle]",[]
"ZÃ¼rich, Zypressenstrasse",47.376662,8.513972,"[ZÃ¼rich, Albisriederplatz, ZÃ¼rich, Lochergut]",[]
"ZÃ¼rich, Lochergut",47.375366,8.517826,"[ZÃ¼rich, Zypressenstrasse, ZÃ¼rich,Kalkbreite/B...",[]
"ZÃ¼rich, Sihlpost / HB",47.376339,8.534570,"[ZÃ¼rich, Stauffacher, ZÃ¼rich, LÃ¶wenplatz]","[ZÃ¼rich, LÃ¶wenplatz, ZÃ¼rich, Kanonengasse]"
"ZÃ¼rich, Seebach",47.421694,8.549958,"[ZÃ¼rich, Seebacherplatz]",[]
...,...,...,...,...
"ZÃ¼rich, Feldeggstrasse",47.360490,8.552042,"[ZÃ¼rich, Kreuzstrasse, ZÃ¼rich, HÃ¶schgasse]",[]
"ZÃ¼rich, FÃ¶rrlibuckstrasse",47.392220,8.517439,"[ZÃ¼rich, Fischerweg, ZÃ¼rich, Escher-Wyss-Platz]",[]
"ZÃ¼rich, Uetlihof",47.356589,8.513819,"[ZÃ¼rich, Strassenverkehrsamt, ZÃ¼rich, Laubegg]",[]
"ZÃ¼rich, Bahnhof Enge/Bederstr.",47.364536,8.530222,"[ZÃ¼rich, Tunnelstrasse, ZÃ¼rich, Waffenplatzstr...",[]
"ZÃ¼rich, Wartau",47.402667,8.492098,"[ZÃ¼rich, Winzerstrasse, ZÃ¼rich, Zwielplatz]",[]

In [18]:
station_info_csv = station_info.to_csv("station_info", index=True)